### PR TITLE
Reduce PNG file size by about 20% using zopflipng 1.0.3 (losslessly)

### PR DESCRIPTION
**Pull request by hartwork**
```console
# for i in *.png ; do zopflipng -y $i $i ; done
Optimizing oela-icon-lg-padding.png
Input size: 89708 (87K)
Result size: 68101 (66K). Percentage of original: 75.914%
Result is smaller

Optimizing oela-icon-lg.png
Input size: 213023 (208K)
Result size: 169235 (165K). Percentage of original: 79.444%
Result is smaller

Optimizing oela-icon.png
Input size: 18674 (18K)
Result size: 15273 (14K). Percentage of original: 81.788%
Result is smaller
```

https://github.com/google/zopfli

### CODE REVIEW

**Comment by hartwork** [comment]
@gmkurtzer do you have a minute for this? What do you think?

**Review by dirkmueller — APPROVED** [review]

**Comment by dirkmueller** [comment]
I'm not greg but it seems obvious enough. BTW, these assets are copied also elsewhere, like openela.org.

**Comment by hartwork** [comment]
> I'm not greg but it seems obvious enough. BTW, these assets are copied also elsewhere, like openela.org.

@dirkmueller thank you! I have created https://github.com/openela/openela.org/pull/25 now to address the same over there. Are you aware of any other repository that could use a change like that?

**Comment by dirkmueller** [comment]
No, I think that's everything that is in GitHub. Thank you very much for the extra PR!

**Pull request merged**
